---
# https://console.redhat.com/ansible/automation-hub/repo/validated/infra/aap_configuration/docs/
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
  - name: infra.aap_configuration